//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFoot
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentTypes()
        {
            this.UserData = new HashSet<UserData>();
        }
    
        public int ContentTypeID { get; set; }
        public string ContentType { get; set; }
        public string PreHTML { get; set; }
        public string PostHTML { get; set; }
        public string UserCss { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserData> UserData { get; set; }
    }
}
