//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFoot
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenus
    {
        public int SubMenuID { get; set; }
        public string SubMenu { get; set; }
        public string smUrl { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> PageID { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Pages Pages { get; set; }
    }
}
