//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFoot
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int UDID { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<int> ContentTypeID { get; set; }
        public string Udata { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual ContentTypes ContentTypes { get; set; }
    }
}
